project:
  type: book
  resources:
    - chapters/notebook_gallery/notebooks/GMCI_notebook_template/notebook.qmd

book:
  title: "Graphical Modeling and Causal Inference"
  author: 
    name: "MaRDI@TUM"
    url: https://portal.mardi4nfdi.de/wiki/Portal/TA3
  date: today
  favicon: "images/arrow_orange.png"
  repo-url: https://github.com/MaRDI4NFDI/StMaRDI
  sidebar: 
    style: "floating"
    collapse-level: 1
    border: true
    search: true
  page-footer:
    left: |
      All content is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) unless otherwise stated. <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="/images/by-nc-sa.png" alt="CC BY-NC-SA 4.0" style="height:20px; vertical-align:baseline;"></a> 
    right: | 
      <div style="height: 20px; width = 10px"></div>
      [Imprint](/chapters/imprint.txt). 
      &copy; [MaRDI@TUM](https://portal.mardi4nfdi.de/wiki/Portal/TA3) </br>
    center: |
      <div style = "overflow: hidden; display: inline-block; vertical-align: center;">
      <img src="/images/MaRDI_Logo.png" alt="MaRDI Logo" style="height: 30px;">
      </div>
    background: "#f8f9fa"
  chapters:
    - index.qmd
    - text: "About"
      file: chapters/about.qmd
    - chapters/datasets.qmd
    - part: chapters/notebooks.qmd
      chapters: 
        - text: "PC Algorithm for Causal Discovery"
          file: chapters/notebook_gallery/notebooks/PC_Alg/notebook.qmd
        - text: "ALARM Subgraph Analysis"
          file: chapters/notebook_gallery/notebooks/alarm_subgraph_analysis/notebook.qmd
        - text: "SEMID Notebook"
          file: chapters/notebook_gallery/notebooks/GMCI-notebook-SEMID/notebook.qmd
        - text: "OSCAR Linear ID Notebook"
          file: chapters/notebook_gallery/notebooks/OscarID/notebook.qmd
        - text: "CausalDynamics Benchmark"
          file: chapters/notebook_gallery/notebooks/CausalDynamics/notebook.qmd
        - text: "Cost-Aware Experimental Design"
          file: chapters/notebook_gallery/notebooks/Cost-Aware-Experimental-Design/notebook.qmd
        - text: "Analysis Notebook Template"
          file: chapters/notebook_gallery/notebooks/GMCI_notebook_template/notebook.qmd
        - text: "Julia Notebook Template"
          file: chapters/notebook_gallery/notebooks/GMCI_Julia_notebook/notebook.qmd
    - chapters/contribute.qmd

bibliography: chapters/references.bib


format:
  html:
    theme:
      light: cosmo
      dark: darkly
    documentclass: scrreprt
    code-overflow: wrap # wrap long code
    number-depth: 3 # number headings until level 3 (###)
    toc: true # table of content
    toc-location: right
    toc-expand: true
    reference-location: margin # references in notebook margin
    citation-location: margin
    css: custom.css
      
execute:
  cache: true
