project:
  type: book

book:
  title: "Graphical Modelling and Causal Inference"
  author: "MaRDI@TUM"
  date: "6/27/2025"
  favicon: "images/arrow_round.png"
  page-footer:
    left: |
      All content licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: | 
      <div style="height: 20px; width = 10px"></div>
      [Imprint](chapters/imprint.txt). 
      &copy; [MaRDI@TUM](https://portal.mardi4nfdi.de/wiki/Portal/TA3) </br>
    center: |
      <div style = "overflow: hidden; display: inline-block; vertical-align: center;">
      <img src="images/MaRDI_Logo.png" alt="MaRDI Logo" style="height: 30px; margin-right: 20px;">
      <img src="images/TUM_Logo.PNG" alt="TUM Logo" style="height: 30px;">
      </div>
    background: "#f8f9fa"
  chapters:
    - index.qmd
    - part: chapters/notebooks.qmd
      chapters: 
        - chapters/notebook_gallery/notebook2.qmd
        - chapters/notebook_gallery/notebook3.qmd
    - chapters/contribute.qmd
    - chapters/references.qmd

bibliography: chapters/references.bib

format:
  html:
    theme: cosmo
    documentclass: scrreprt
    cover-image: images/cover.png
    number-depth: 3
    grid: 
      margin-width: 0px
      gutter-width: 2rem
      
execute:
  cache: true
