project:
  type: book

book:
  title: "Graphical Modelling and Causal Inference"
  author: "MaRDI@TUM"
  date: "2/13/2025"
  chapters:
    - index.qmd
    - zenodo_search.qmd
    - custom_online_data_search.qmd
    - part: notebooks.qmd
      chapters: 
        - gallery/notebook1.qmd
        - gallery/notebook2.qmd
        - gallery/notebook3.qmd
        - gallery/notebook4.qmd
        - gallery/notebook5.qmd
    - contribute.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    documentclass: scrreprt
    grid: 
      margin-width: 0px
      gutter-width: 2rem
editor: visual