project:
  type: book

book:
  title: "GMCI_MaRDI"
  author: "MaRDI@TUM"
  date: "2/4/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - part: gallery.qmd
      chapters: 
        - gallery/notebook1.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    documentclass: scrreprt
    grid: 
      margin-width: 0px
      gutter-width: 2rem
editor: visual