name: Publish Quarto Book

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_AUTH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.5.57'

      - name: Render the book
        run: quarto render

      - name: Publish to Quarto Pub
        run: quarto publish quarto-pub
